create table if not exists incidents (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) >= 5),
  description text not null check (char_length(trim(description)) >= 10),
  category text not null check (
    category in (
      'POS Issue',
      'Delivery Delay',
      'Inventory',
      'Kitchen Equipment',
      'Customer Complaint',
      'Other'
    )
  ),
  store_location text not null check (char_length(trim(store_location)) > 0),
  severity text not null check (severity in ('Low', 'Medium', 'High', 'Critical')),
  status text not null default 'Open' check (status in ('Open', 'In Progress', 'Resolved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists incidents_created_at_idx on incidents (created_at desc);
create index if not exists incidents_category_idx on incidents (category);
create index if not exists incidents_severity_idx on incidents (severity);
create index if not exists incidents_status_idx on incidents (status);
